//login to Agent-1 here wwe are using agent ec2 so login to that manually through super putty 
//do sudo visudo or sudo cd /etc/sudoers file 
// add jenkins ALL=(ALL) NOPASSWD: ALL   after %wheel 
// this is adding becasue it will not run as root it will run as jenkins user so adding like this 
//do aws configure command not in root user do it in normal user in agent-1 where ever agent u do all this
//then only pipeline will execute and one for one ec2/agent/jenins server

pipeline {
    agent {
        node {
            label 'Agent-1'
        }
    }
    environment {
        packageVersion = ''
    }
    options {
        ansiColor('xterm')
        timeout(time:1, unit:'HOURS')
        disableConcurrentBuilds()
    }

    stages {
        stage('Get Version') {
            steps {
                script {
                    sh 'cd catalogue/'
                    def packageJSON = readJSON file: 'catalogue/package.json'
                    packageVersion = packageJSON.version
                    echo "Application version is : $packageVersion"
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                sh """
                    sudo dnf module disable nodejs -y
                    sudo dnf module enable nodejs:18 -y
                    sudo dnf install nodejs -y
                    cd catalogue/
                    npm install  
                """
            }
        }
        stage('Build') {
            steps {
                sh """
                    ls -la catalogue/
                    sudo dnf install zip -y
                    zip -q -r catalogue.zip ./* -x ".git" -x ".zip"
                    ls -ltr catalogue/
                """
            }
        }
    }
    post {
        always {
            echo "Always runs whether pipeline success or failure"
            deleteDir()

        }
        success {
            echo "Pipeline is runned successfully "
        }
        failure {
            echo "Pipeline is Failed "
        }
    }
}