//login to Agent-1 here wwe are using agent ec2 so login to that manually through super putty 
//do sudo visudo or sudo cd /etc/sudoers file 
// add jenkins ALL=(ALL) NOPASSWD: ALL   after %wheel 
// this is adding becasue it will not run as root it will run as jenkins user so adding like this 
//do aws configure command not in root user do it in normal user in agent-1 where ever agent u do all this
//then only pipeline will execute and one for one ec2/agent/jenins server

pipeline {
    agent {
        node {
            label 'Agent-1'
        }
    }
    environment {
        packageVersion = ''
        nexusURL = 'nexus.devopswitharun.online:8081'   //we gave public ip by creating route53 record of nexus ec2 with port but in project we use static ip 
    }
    options {
        ansiColor('xterm')
        timeout(time:1, unit:'HOURS')
        disableConcurrentBuilds()
    }
    parameters {
        booleanParam(name: 'Deploy', defaultValue: false, description: 'If Deploy Want Do  This ?')
    }
    stages {
        stage('Get Version') {
            steps {
                script {
                    sh 'cd catalogue/'
                    def packageJSON = readJSON file: 'catalogue/package.json'
                    packageVersion = packageJSON.version
                    echo "Application version is : $packageVersion"
                }
            }
        }
    }
    post {
        always {
            echo "Always runs whether pipeline success or failure"
            deleteDir()

        }
        success {
            echo "Pipeline is runned successfully "
        }
        failure {
            echo "Pipeline is Failed "
        }
    }
}