pipeline {
    agent {
        node {
            label 'Agent-1'
        }
    }
    environment {
        packageVersion = ''
    }
    options {
        ansiColor('xterm')
        timeout(time:1, unit:'HOURS')
        disableConcurrentBuilds()
    }

    stages {
        stage('Get Version') {
            steps {
                script {
                    sh 'cd catalogue/'
                    def packageJSON = readJSON file: 'catalogue/package.json'
                    packageVersion = packageJSON.version
                    echo "Application version is : $packageVersion"
                }
            }
        }
    }
    post {
        always {
            echo "Always runs whether pipeline success or failure"
        }
    }
}