#----- Default SonarQube server
sonar.host.url=http://sonarqube.devopswitharun.online:9000
sonar.projectKey=catalogue
sonar.projectName=catalogue
sonar.login=sqa_06f281f68b1266e3d914c6c4a398febb54c5d1f6

sonar.qualitygate.wait=true 
sonar.exclusions=node_modules**  






#above details u can give in agent ec2 because we installed scanner-cli in agent ec2  in agent ec2 --> go to cd /opt/sonar/conf --> u will find a file name called --> sonar-scanner.properties 
#or u can give all details here also 
